### ISSUE TITLE
Version 1.3.3's Mac version has incorrect permissions

### ISSUE THREAD

**Issue by ticky** [sonik-br/GDMENUCardManager#11]
The current Mac version does not run due to a permission error; the executables at `GDMENUCardManager.app/Contents/MacOS/GDMENU` and `GDMENUCardManager.app/Contents/MacOS/GDMENUCardManager/GDMENUCardManager` are not marked as executable, which causes the app to fail to open until manually fixed.

**Comment by sonik-br** [comment]
I have no means to flag it as executable. I don't even have access to a mac.
It's not working as an "application bundle" ?
Please see issue number #4

**Comment by ticky** [comment]
No, the application bundle does not work as provided; those two specific files need to be marked executable for it to work. The build provided by @Pistacchione in #4 _does_ work because the permissions are already correct, but the one in [`GDMENUCardManager.v1.3.3-osx-x64-AppBundle.zip`](https://github.com/sonik-br/GDMENUCardManager/releases/tag/1.3.3) does not.

You might consider building the releases using GitHub's Actions CI, which provides free Mac environments to build on.

**Comment by sonik-br** [comment]
I have no idea how to do this.
I will revert back to not using the bundle then.
For now you can just extract it from the zip and set the correct attributes right?

**Comment by ticky** [comment]
Right, well looking at what Avalonia say they sadly don't have a good suggestion for this, other than [doing `chmod` stuff on a Unix system](https://docs.avaloniaui.net/docs/distribution-publishing/macos#manual). Do you have access to a Linux machine to do this? That should work, as long as the files are marked correctly.

**Comment by ticky** [comment]
It looks like there might be a way to fix this from Windows, using [this person's tool](https://stackoverflow.com/a/66931153)

**Comment by Pistacchione** [comment]
Try to do `chmod +x GDMENU` and `chmod +x GDMENUCardManager/GDMENUCardManager` inside `Contents/MacOS` folder. Doing this should fix the permission error inside bundle app

**Comment by sonik-br** [comment]
I've made a python script to create the linux tar version with the correct attribute.
Passed the mac version through it and generated a tar.gz file.
It's on the releases page. Can you test it please?

**Comment by YunaVirtua** [comment]
I've tested it with the tar.gz bundle, applying `chmod +x` to GDMENU makes it executable, but without doing that the issue persists

**Comment by ticky** [comment]
Your script might only be applying +x to `GDMENUCardManager.app/Contents/MacOS/GDMENUCardManager/GDMENUCardManager`, it'll need to apply it to `GDMENUCardManager.app/Contents/MacOS/GDMENU` as well.

I just want to say I appreciate you working to help with this!

**Comment by sonik-br** [comment]
Oh. I will need to apply the correct attribute to the GDMENU shell script too.
Gonna do this in a few days. Will let you know.
Also thanks for testing and reporting! It's really important to me as I don't have access to a mac.

**Comment by Pistacchione** [comment]
Hi to all,

as @ticky said it need to apply +x to `GDMENUCardManager.app/Contents/MacOS/GDMENU`.

Application start but with access denied error on every volume
![immagine](https://user-images.githubusercontent.com/11761177/124459715-b95e6d80-dd8e-11eb-8a60-802d43878848.png)

But if you start it via command line `./GDMENUCardManager.app/Contents/MacOS/GDMENU` it works...
![GDMENU](https://user-images.githubusercontent.com/11761177/124460171-50c3c080-dd8f-11eb-8fbc-e00d90a5c570.png)

We need to investigate more to find the issue.

By the way, this is a great tool and we hope to help you solve this issue and improve it further!

**Comment by sonik-br** [comment]
Uploaded AppBundle.tar.gz with execute attribute on the two required files.
Please test again. :)

**Comment by Pistacchione** [comment]
> Uploaded AppBundle.tar.gz with execute attribute on the two required files.
> Please test again. :)

Now the application start but all external volumes are not accessible
![immagine](https://user-images.githubusercontent.com/11761177/124560464-1d3f6f80-de3d-11eb-9520-7c69df13ba43.png)

**Comment by sonik-br** [comment]
One more time... Now using the linked "zip_exec" program.
Please try again with the zip file.

**Comment by Pistacchione** [comment]
> One more time... Now using the linked "zip_exec" program.
> Please try again with the zip file.

Nope, same error for me

**Comment by sonik-br** [comment]
Ouch. Getting out of options here.
If you get the normal zip version, extract and set attribute on the executable, it works?

**Comment by ticky** [comment]
> Now the application start but all external volumes are not accessible
> ![immagine](https://user-images.githubusercontent.com/11761177/124560464-1d3f6f80-de3d-11eb-9520-7c69df13ba43.png)

this is an entirely separate issue and *not* related to the executable flag, let's discuss that one in #12

it sounds like the `tar.gz` solution worked for this, but that version seems to have been deleted now, so I can't check!

**Comment by ticky** [comment]
The current `zip` version also has correct executable permissions, so I believe this particular issue is resolved.

**Comment by sonik-br** [comment]
@ticky tar file is back again but it should have the exactly same attributes as the zip one.
If you want to test it.

**Comment by Pistacchione** [comment]
> @ticky tar file is back again but it should have the exactly same attributes as the zip one.
> If you want to test it.

Maybe this doc could help to build a correct `.app` application https://docs.avaloniaui.net/docs/distribution-publishing/macos#notes-on-the-app-executable-file

**Comment by ticky** [comment]
@sonik-br okay, that version works, too 👍🏼 whichever way is easiest for you, this issue is resolved
